apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: monitoring-app
  namespace: avengers
  labels:
    app: monitoring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
      - name: monitoring-app
        image: mahi4847/monitoring-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-app-c
  namespace: avengers
  labels:
    app: monitoring-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: monitoring-app
